env:
- DISPLAY: ":99.0"
sudo: false
cache: npm
language: node_js
node_js:
  - 6
install:
  - npm install
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm test
